### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by FantasticFiasco** [choclaudio/bliss.js#1]
Build project on [Travis](https://travis-ci.org/) or whatever CI you decide to choose.

Building in the current state of the project would be linting, nothing more, but at the time you add tests those could be exercised as well.

**Comment by choclaudio** [comment]
Yes, I agree. Why not integrate CI with linting now rather than later.

**Comment by FantasticFiasco** [comment]
If you are experiencing with any problems, let me know and I'll see if I can help you

**Comment by choclaudio** [comment]
@FantasticFiasco Solved in https://github.com/choclaudio/bliss.js/commit/60d571b121cd1dbb3ce1f35db17fd4201ceaa7ec

Things to improve next time, make sure to refer to the issue in the commit message, probably do a PR aswell.
