### ISSUE TITLE
Evergreen dependencies

### ISSUE THREAD

**Issue by FantasticFiasco** [choclaudio/bliss.js#2]
Keep your dependencies up-to-date by letting [Greenkeeper](https://greenkeeper.io/) create PR for you when dependencies are updated.

**Comment by choclaudio** [comment]
Activated greenkeeper and added greenkeeper-lockfile commit: https://github.com/choclaudio/bliss.js/commit/c33d3106614372b202ee2f9c877b14b411d07540
