### ISSUE TITLE
Travis build badge

### ISSUE THREAD

**Issue by FantasticFiasco** [choclaudio/bliss.js#5]
To be cool you have to add as many badges as you can to your `README.md`. Start by adding the Travis build badge. By doing so you will level up to the status of "Awesome".

Perks gained by being "Awesome" is that you now have the permissions to buy a sticker of my face to place on your laptop. The sticker is ugly as fuck, but will infuse respect, or sickness, among your peers.

Btw, as payment I only accept Bitcoin from December...

**Comment by choclaudio** [comment]
I will hold you accountable for the sticker, you can get a bit from my coin!
